In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("MY2022 Fuel Consumption Ratings.csv")

In [3]:
df

,Model Year,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption (City (L/100 km),Fuel Consumption(Hwy (L/100 km)),Fuel Consumption(Comb (L/100 km)),Fuel Consumption(Comb (mpg)),CO2 Emissions(g/km),CO2 Rating,Smog Rating
0,2022,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,200,6,3
1,2022,Acura,MDX SH-AWD,SUV: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
2,2022,Acura,RDX SH-AWD,SUV: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232,5,6
3,2022,Acura,RDX SH-AWD A-SPEC,SUV: Small,2.0,4,AS10,Z,11.3,9.1,10.3,27,242,5,6
4,2022,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,11.2,8.0,9.8,29,230,5,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,2022,Volvo,XC40 T5 AWD,SUV: Small,2.0,4,AS8,Z,10.7,7.7,9.4,30,219,5,5
942,2022,Volvo,XC60 B5 AWD,SUV: Small,2.0,4,AS8,Z,10.5,8.1,9.4,30,219,5,5
943,2022,Volvo,XC60 B6 AWD,SUV: Small,2.0,4,AS8,Z,11.0,8.7,9.9,29,232,5,7
944,2022,Volvo,XC90 T5 AWD,SUV: Standard,2.0,4,AS8,Z,11.5,8.4,10.1,28,236,5,5
945,2022,Volvo,XC90 T6 AWD,SUV: Standard,2.0,4,AS8,Z,12.4,8.9,10.8,26,252,5,7

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 946 entries, 0 to 945
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Model Year                         946 non-null    int64
 1   Make                               946 non-null    object
 2   Model                              946 non-null    object
 3   Vehicle Class                      946 non-null    object
 4   Engine Size(L)                     946 non-null    float64
 5   Cylinders                          946 non-null    int64
 6   Transmission                       946 non-null    object
 7   Fuel Type                          946 non-null    object
 8   Fuel Consumption (City (L/100 km)  946 non-null    float64
 9   Fuel Consumption(Hwy (L/100 km))   946 non-null    float64
 10  Fuel Consumption(Comb (L/100 km))  946 non-null    float64
 11  Fuel Consumption(Comb (mpg))       946 non-null    int64
 12  CO2 Emissions(g/km)                946 non-null    int64
 13  CO2 Rating                         946 non-null    int64
 14  Smog Rating                        946 non-null    int64
dtypes: float64(4), int64(6), object(5)
memory usage: 111.0+ KB

In [5]:
df.describe()

,Model Year,Engine Size(L),Cylinders,Fuel Consumption (City (L/100 km),Fuel Consumption(Hwy (L/100 km)),Fuel Consumption(Comb (L/100 km)),Fuel Consumption(Comb (mpg)),CO2 Emissions(g/km),CO2 Rating,Smog Rating
count,946.0,946.000000,946.000000,946.000000,946.000000,946.000000,946.000000,946.000000,946.000000,946.000000
mean,2022.0,3.198732,5.668076,12.506448,9.363319,11.092072,27.247357,259.172304,4.539112,4.950317
std,0.0,1.374814,1.932670,3.452043,2.285125,2.876276,7.685217,64.443149,1.471799,1.679842
min,2022.0,1.200000,3.000000,4.000000,3.900000,4.000000,11.000000,94.000000,1.000000,1.000000
25%,2022.0,2.000000,4.000000,10.200000,7.700000,9.100000,22.000000,213.250000,3.000000,3.000000
50%,2022.0,3.000000,6.000000,12.200000,9.200000,10.800000,26.000000,257.000000,5.000000,5.000000
75%,2022.0,3.800000,6.000000,14.700000,10.700000,12.900000,31.000000,300.750000,5.000000,6.000000
max,2022.0,8.000000,16.000000,30.300000,20.900000,26.100000,71.000000,608.000000,10.000000,7.000000

In [6]:
df.isnull().sum()

Model Year                           0
Make                                 0
Model                                0
Vehicle Class                        0
Engine Size(L)                       0
Cylinders                            0
Transmission                         0
Fuel Type                            0
Fuel Consumption (City (L/100 km)    0
Fuel Consumption(Hwy (L/100 km))     0
Fuel Consumption(Comb (L/100 km))    0
Fuel Consumption(Comb (mpg))         0
CO2 Emissions(g/km)                  0
CO2 Rating                           0
Smog Rating                          0
dtype: int64

In [7]:
df.shape

(946, 15)

In [8]:
df.columns

Index(['Model Year', 'Make', 'Model', 'Vehicle Class', 'Engine Size(L)',
       'Cylinders', 'Transmission', 'Fuel Type',
       'Fuel Consumption (City (L/100 km)', 'Fuel Consumption(Hwy (L/100 km))',
       'Fuel Consumption(Comb (L/100 km))', 'Fuel Consumption(Comb (mpg))',
       'CO2 Emissions(g/km)', 'CO2 Rating', 'Smog Rating'],
      dtype='object')

In [9]:
df.drop(columns=["Model Year",'Fuel Consumption (City (L/100 km)','Fuel Consumption(Hwy (L/100 km))','Fuel Consumption(Comb (L/100 km))','CO2 Rating',],inplace=True)
df.head(3)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption(Comb (mpg)),CO2 Emissions(g/km),Smog Rating
0,Acura,ILX,Compact,2.4,4,AM8,Z,33,200,3
1,Acura,MDX SH-AWD,SUV: Small,3.5,6,AS10,Z,25,263,5
2,Acura,RDX SH-AWD,SUV: Small,2.0,4,AS10,Z,29,232,6

In [10]:
l=["make","model","vehicle_class","engine","cylinder","transmission","fuel","consumption","co2","smokerating"]
l

['make',
 'model',
 'vehicle_class',
 'engine',
 'cylinder',
 'transmission',
 'fuel',
 'consumption',
 'co2',
 'smokerating']

In [11]:
df.rename(columns={i:j for i,j in zip(df.columns,l)},inplace=True)

In [12]:
df

,make,model,vehicle_class,engine,cylinder,transmission,fuel,consumption,co2,smokerating
0,Acura,ILX,Compact,2.4,4,AM8,Z,33,200,3
1,Acura,MDX SH-AWD,SUV: Small,3.5,6,AS10,Z,25,263,5
2,Acura,RDX SH-AWD,SUV: Small,2.0,4,AS10,Z,29,232,6
3,Acura,RDX SH-AWD A-SPEC,SUV: Small,2.0,4,AS10,Z,27,242,6
4,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,29,230,7
...,...,...,...,...,...,...,...,...,...,...
941,Volvo,XC40 T5 AWD,SUV: Small,2.0,4,AS8,Z,30,219,5
942,Volvo,XC60 B5 AWD,SUV: Small,2.0,4,AS8,Z,30,219,5
943,Volvo,XC60 B6 AWD,SUV: Small,2.0,4,AS8,Z,29,232,7
944,Volvo,XC90 T5 AWD,SUV: Standard,2.0,4,AS8,Z,28,236,5
945,Volvo,XC90 T6 AWD,SUV: Standard,2.0,4,AS8,Z,26,252,7

In [13]:
qualititive = []
quantitive = []

for i in df.columns:
    if type(df[i].iloc[0]) == str:
        qualititive.append(i)
    else:
        quantitive.append(i)

In [14]:
print("The Qualitative data :\n {},\n The Quantitave data :\n {},\n".format(qualititive,quantitive))

The Qualitative data :
 ['make', 'model', 'vehicle_class', 'transmission', 'fuel'],
 The Quantitave data :
 ['engine', 'cylinder', 'consumption', 'co2', 'smokerating'],

In [15]:
df=df[['make', 'model', 'vehicle_class', 'transmission', 'fuel','engine', 'cylinder', 'co2', 'smokerating', 'consumption']]

In [16]:
df

,make,model,vehicle_class,transmission,fuel,engine,cylinder,co2,smokerating,consumption
0,Acura,ILX,Compact,AM8,Z,2.4,4,200,3,33
1,Acura,MDX SH-AWD,SUV: Small,AS10,Z,3.5,6,263,5,25
2,Acura,RDX SH-AWD,SUV: Small,AS10,Z,2.0,4,232,6,29
3,Acura,RDX SH-AWD A-SPEC,SUV: Small,AS10,Z,2.0,4,242,6,27
4,Acura,TLX SH-AWD,Compact,AS10,Z,2.0,4,230,7,29
...,...,...,...,...,...,...,...,...,...,...
941,Volvo,XC40 T5 AWD,SUV: Small,AS8,Z,2.0,4,219,5,30
942,Volvo,XC60 B5 AWD,SUV: Small,AS8,Z,2.0,4,219,5,30
943,Volvo,XC60 B6 AWD,SUV: Small,AS8,Z,2.0,4,232,7,29
944,Volvo,XC90 T5 AWD,SUV: Standard,AS8,Z,2.0,4,236,5,28
945,Volvo,XC90 T6 AWD,SUV: Standard,AS8,Z,2.0,4,252,7,26

In [17]:
x = df.drop("consumption",axis=1)
y = df["consumption"]

In [18]:
x

,make,model,vehicle_class,transmission,fuel,engine,cylinder,co2,smokerating
0,Acura,ILX,Compact,AM8,Z,2.4,4,200,3
1,Acura,MDX SH-AWD,SUV: Small,AS10,Z,3.5,6,263,5
2,Acura,RDX SH-AWD,SUV: Small,AS10,Z,2.0,4,232,6
3,Acura,RDX SH-AWD A-SPEC,SUV: Small,AS10,Z,2.0,4,242,6
4,Acura,TLX SH-AWD,Compact,AS10,Z,2.0,4,230,7
...,...,...,...,...,...,...,...,...,...
941,Volvo,XC40 T5 AWD,SUV: Small,AS8,Z,2.0,4,219,5
942,Volvo,XC60 B5 AWD,SUV: Small,AS8,Z,2.0,4,219,5
943,Volvo,XC60 B6 AWD,SUV: Small,AS8,Z,2.0,4,232,7
944,Volvo,XC90 T5 AWD,SUV: Standard,AS8,Z,2.0,4,236,5
945,Volvo,XC90 T6 AWD,SUV: Standard,AS8,Z,2.0,4,252,7

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
one = OneHotEncoder(sparse=False,handle_unknown='ignore')

In [21]:
x_dup =pd.DataFrame(one.fit_transform(x.iloc[:,:5]),columns=one.get_feature_names_out())
x_dup

,make_Acura,make_Alfa Romeo,make_Aston Martin,make_Audi,make_BMW,make_Bentley,make_Bugatti,make_Buick,make_Cadillac,make_Chevrolet,...,transmission_AV6,transmission_AV7,transmission_AV8,transmission_M5,transmission_M6,transmission_M7,fuel_D,fuel_E,fuel_X,fuel_Z
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
943,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
944,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [22]:
x.drop(columns=["make","model","vehicle_class","transmission","fuel"],inplace=True)

In [23]:
x

     engine  cylinder  co2  smokerating
0       2.4         4  200            3
1       3.5         6  263            5
2       2.0         4  232            6
3       2.0         4  242            6
4       2.0         4  230            7
..      ...       ...  ...          ...
941     2.0         4  219            5
942     2.0         4  219            5
943     2.0         4  232            7
944     2.0         4  236            5
945     2.0         4  252            7

[946 rows x 4 columns]

In [24]:
x = pd.concat([x,x_dup],axis=1)
x

,engine,cylinder,co2,smokerating,make_Acura,make_Alfa Romeo,make_Aston Martin,make_Audi,make_BMW,make_Bentley,...,transmission_AV6,transmission_AV7,transmission_AV8,transmission_M5,transmission_M6,transmission_M7,fuel_D,fuel_E,fuel_X,fuel_Z
0,2.4,4,200,3,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3.5,6,263,5,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2.0,4,232,6,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2.0,4,242,6,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,2.0,4,230,7,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,2.0,4,219,5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
942,2.0,4,219,5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
943,2.0,4,232,7,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
944,2.0,4,236,5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
945,2.0,4,252,7,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [25]:
import joblib

In [26]:
joblib.dump(one,"OneHotee.joblib")

['OneHotee.joblib']

In [27]:
from sklearn.ensemble import RandomForestRegressor

In [28]:
model = RandomForestRegressor()

In [29]:
from sklearn.model_selection import GridSearchCV

In [30]:
param_grid={
        "n_estimators":[100,500],
        "max_features":['auto','sqrt','log2'],
        "max_depth":[4,5,6,7,8],
         "criterion":['squared_error']   
}

In [31]:
grid_model = GridSearchCV(estimator=model,param_grid=param_grid,cv=5)

In [32]:
regressor = RandomForestRegressor(n_estimators =100,max_features='auto',max_depth=8,criterion="squared_error")

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=32)

In [35]:
regressor.fit(x_train,y_train)

RandomForestRegressor(max_depth=8, max_features='auto')

In [36]:
regressor.score(x_train,y_train)

0.998277479829632

In [37]:
regressor.score(x_test,y_test)

0.991670060718059

In [38]:
pre = regressor.predict(x_test)

In [39]:
pre

array([20.00547634, 19.        , 24.99697715, 29.99925   , 59.61      ,
       26.89022222, 30.99952381, 23.00055556, 30.34958333, 24.99697715,
       30.01925   , 33.82      , 39.23875   , 23.00105556, 28.99906419,
       41.95      , 24.04332014, 36.08990075, 41.87      , 33.64666667,
       19.        , 18.91      , 57.01      , 27.03508041, 31.03      ,
       28.52421351, 24.99697715, 23.02123737, 21.99948413, 21.99948413,
       39.93875   , 27.00173785, 33.18666667, 28.99906419, 21.99948413,
       33.27      , 19.98547634, 21.99948413, 26.00014626, 36.99436628,
       17.        , 20.00492078, 26.00014626, 20.00547634, 21.98948413,
       35.73780811, 24.99697715, 22.99055556, 23.00055556, 19.        ,
       30.01925   , 24.99697715, 27.32022222, 39.94875   , 21.00154589,
       19.        , 20.23282363, 21.01154589, 63.62      , 24.08155359,
       25.98299777, 20.00492078, 24.01352847, 27.79473356, 29.98966667,
       37.12441258, 23.22437301, 21.99948413, 34.69519913, 23.04123737,
       23.00105556, 22.70055556, 24.01352847, 39.98875   , 30.99952381,
       27.84773356, 39.95875   , 21.00154589, 43.61      , 22.50003968,
       33.99      , 27.80473356, 30.99952381, 39.02      , 23.00105556,
       31.02952381, 20.00492078, 23.01105556, 14.65978723, 20.00492078,
       18.        , 40.93      , 18.        , 36.17421262, 18.46      ,
       47.2       , 20.99154589, 22.06948413, 29.19031938, 19.        ,
       30.01925   , 35.74285597, 21.99948413, 19.        , 19.        ,
       29.18031938, 22.97055556, 33.02666667, 30.99952381, 22.99055556,
       29.98925   , 29.67925   , 41.99      , 18.34      , 23.01055556,
       21.99948413, 23.00105556, 17.        , 32.91      , 28.75030303,
       28.99906419, 30.97952381, 26.00014626, 25.6       , 25.99014626,
       32.63285714, 26.00014626, 46.89      , 36.95672318, 24.01352847,
       30.99952381, 24.99697715, 18.        , 27.0621947 , 19.        ,
       31.99952381, 24.01352847, 23.92485922, 29.70102632, 21.99948413,
       34.71319913, 29.99925   , 24.99697715, 20.01492078, 26.19014626,
       29.99925   , 36.00640145, 31.29952381, 21.99948413, 30.09925   ,
       33.96      , 25.99299777, 34.95519913, 34.95933333, 26.89022222,
       30.99952381, 19.        , 24.04332014, 23.02105556, 20.11483048,
       30.97952381, 21.99948413, 28.64669214, 24.99697715, 36.97709356,
       31.89      , 20.00547634, 22.11      , 34.42519913, 20.00547634,
       53.75      , 29.99925   , 30.97952381, 22.58003968, 20.00492078,
       27.00466375, 20.00492078, 29.99925   , 20.99154589, 29.19031938,
       33.74      , 32.65285714, 19.        , 22.99055556, 22.07948413,
       28.99906419, 28.99906419, 21.92948413, 21.99948413, 21.99948413,
       23.91528032, 19.        , 24.01352847, 33.71666667, 26.95022222,
       27.05483651, 14.33      , 29.38145489, 29.99925   , 35.18431303,
       25.99014626, 20.00492078, 26.18014626, 19.        , 21.99948413,
       24.98697715, 33.97      , 30.01925   , 27.92022222, 19.04      ,
       29.99925   , 14.3       , 28.48338017, 59.2       , 36.93897318,
       24.08223502, 22.98923004, 39.02875   , 27.00173785, 19.88547634,
       31.99952381, 12.61      , 36.96672318, 26.00014626, 24.01352847,
       61.08      , 31.99952381, 26.18070865, 20.66278769, 19.        ,
       16.97      , 20.00547634, 31.95      , 25.99299777, 33.05666667,
       29.99925   , 17.        , 30.61952381, 23.00105556, 29.51864722,
       20.00492078, 28.99906419, 30.99952381, 29.99925   , 24.99697715,
       32.63285714, 21.99948413, 17.        , 24.03332014, 31.05      ,
       61.06      , 24.98697715, 24.01352847, 30.99952381, 19.        ,
       28.85878641, 14.3       , 20.00547634, 33.97      , 29.99925   ,
       24.99697715, 18.        , 27.00173785, 20.00547634, 19.04      ,
       27.00264694, 26.00014626, 21.93948413, 39.26875   , 29.98966667,
       31.99952381, 25.87      , 24.01352847, 26.00014626, 28.00116093,
       39.        , 33.93      , 36.08989962, 21.99948413, 18.        ,
       42.        , 38.        , 30.99952381, 31.95      ])

In [40]:
from sklearn.metrics import mean_squared_error,r2_score

In [41]:
mean_squared_error(y_test,pre)

0.5744356327128556

In [42]:
r2_score(y_test,pre)

0.991670060718059

In [43]:
np.sqrt(mean_squared_error(y_test,pre))

0.7579153202784963

In [44]:
joblib.dump(regressor,"regressor.pkl")

['regressor.pkl']

In [45]:
check=df.copy()

In [46]:
check=check.head(1)
check

,make,model,vehicle_class,transmission,fuel,engine,cylinder,co2,smokerating,consumption
0,Acura,ILX,Compact,AM8,Z,2.4,4,200,3,33

In [47]:
check.drop("consumption",axis=1,inplace=True)

In [48]:
check

,make,model,vehicle_class,transmission,fuel,engine,cylinder,co2,smokerating
0,Acura,ILX,Compact,AM8,Z,2.4,4,200,3

In [49]:
one_hot = joblib.load("OneHotee.joblib")
one_hot

OneHotEncoder(handle_unknown='ignore', sparse=False)

In [50]:
l=one_hot.transform(check.iloc[:,:5])
l

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [51]:
c = one_hot.get_feature_names_out()

In [52]:
c

array(['make_Acura', 'make_Alfa Romeo', 'make_Aston Martin', 'make_Audi',
       'make_BMW', 'make_Bentley', 'make_Bugatti', 'make_Buick',
       'make_Cadillac', 'make_Chevrolet', 'make_Chrysler', 'make_Dodge',
       'make_FIAT', 'make_Ford', 'make_GMC', 'make_Genesis', 'make_Honda',
       'make_Hyundai', 'make_Infiniti', 'make_Jaguar', 'make_Jeep',
       'make_Kia', 'make_Lamborghini', 'make_Land Rover', 'make_Lexus',
       'make_Lincoln', 'make_MINI', 'make_Maserati', 'make_Mazda',
       'make_Mercedes-Benz', 'make_Mitsubishi', 'make_Nissan',
       'make_Porsche', 'make_Ram', 'make_Rolls-Royce', 'make_Subaru',
       'make_Toyota', 'make_Volkswagen', 'make_Volvo', 'model_1500',
       'model_1500 4X4', 'model_1500 4X4 EcoDiesel', 'model_1500 4X4 TRX',
       'model_1500 4X4 eTorque', 'model_1500 Classic',
       'model_1500 Classic 4X4', 'model_1500 EcoDiesel',
       'model_1500 HFE EcoDiesel', 'model_1500 HFE eTorque',
       'model_1500 eTorque', 'model_300', 'model_300 AWD',
       'model_330i xDrive Sedan', 'model_430i xDrive Cabriolet',
       'model_430i xDrive Coupe', 'model_4Runner 4WD',
       'model_4Runner 4WD (Part-Time 4WD) ', 'model_500X AWD',
       'model_530i xDrive Sedan', 'model_540i xDrive Sedan',
       'model_718 Boxster', 'model_718 Boxster GTS 4.0',
       'model_718 Boxster S', 'model_718 Boxster T', 'model_718 Cayman',
       'model_718 Cayman GT4', 'model_718 Cayman GTS 4.0',
       'model_718 Cayman S', 'model_718 Cayman T', 'model_718 Spyder',
       'model_750Li xDrive Sedan', 'model_750i xDrive Sedan',
       'model_911 Carrera', 'model_911 Carrera 4',
       'model_911 Carrera 4 Cabriolet', 'model_911 Carrera 4 GTS',
       'model_911 Carrera 4 GTS Cabriolet', 'model_911 Carrera 4S',
       'model_911 Carrera 4S Cabriolet', 'model_911 Carrera Cabriolet',
       'model_911 Carrera GTS', 'model_911 Carrera GTS Cabriolet',
       'model_911 Carrera S', 'model_911 Carrera S Cabriolet',
       'model_911 GT3', 'model_911 GT3 Touring', 'model_911 Targa 4',
       'model_911 Targa 4 GTS', 'model_911 Targa 4S', 'model_911 Turbo',
       'model_911 Turbo Cabriolet', 'model_911 Turbo S',
       'model_911 Turbo S Cabriolet', 'model_A 220 4MATIC Sedan',
       'model_A 250 4MATIC Hatch', 'model_A3 Sedan 40 TFSI quattro',
       'model_A4 Sedan 40 TFSI quattro', 'model_A4 Sedan 45 TFSI quattro',
       'model_A4 allroad 45 TFSI quattro',
       'model_A5 Cabriolet 45 TFSI quattro',
       'model_A5 Coupe 45 TFSI quattro',
       'model_A5 Sportback 45 TFSI quattro',
       'model_A6 Sedan 45 TFSI quattro', 'model_A6 Sedan 55 TFSI quattro',
       'model_A6 allroad 55 TFSI quattro',
       'model_A7 Sportback 55 TFSI quattro',
       'model_A8 L Sedan 55 TFSI quattro', 'model_AMG A 35 4MATIC Hatch',
       'model_AMG A 35 4MATIC Sedan', 'model_AMG C 43 4MATIC Cabriolet',
       'model_AMG C 43 4MATIC Coupe', 'model_AMG CLA 35 4MATIC Coupe',
       'model_AMG CLA 45 4MATIC Coupe', 'model_AMG CLS 53 4MATIC+ Coupe',
       'model_AMG E 53 4MATIC+ Cabriolet', 'model_AMG E 53 4MATIC+ Coupe',
       'model_AMG E 53 4MATIC+ Sedan', 'model_AMG GLA 35 4MATIC SUV',
       'model_AMG GLA 45 4MATIC SUV', 'model_AMG GLB 35 4MATIC SUV',
       'model_AMG GLC 43 4MATIC Coupe', 'model_AMG GLC 43 4MATIC SUV',
       'model_AMG GLE 53 4MATIC+ Coupe', 'model_AMG GLE 53 4MATIC+ SUV',
       'model_AMG GT 53 4MATIC+ Coupe', 'model_Acadia',
       'model_Acadia AWD', 'model_Accord', 'model_Accord Hybrid',
       'model_Accord Hybrid Sport/Touring', 'model_Accord Sport/Touring',
       'model_Alpina B7', 'model_Alpina B8 Gran Coupe',
       'model_Alpina XB7', 'model_Altima AWD',
       'model_Altima AWD SR/Platinum', 'model_Armada 4WD',
       'model_Ascent AWD', 'model_Atlas 4MOTION',
       'model_Atlas Cross Sport 4MOTION', 'model_Aventador Countach',
       'model_Aventador Coupe', 'model_Aventador Roadster',
       'model_Aviator AWD', 'model_BRZ', 'model_Bentayga',
       'model_Bentayga Speed', 'model_Blazer', 'model_Blazer AWD',
       'model_Bronco 4WD', 'model_Bronco Badlands 4WD',
       'model_Bronco Black Diamond 4WD', 'model_Bronco Sasquatch 4WD',
       'model_Bronco Sport 4WD', 'model_C 300 4MATIC Cabriolet',
       'model_C 300 4MATIC Coupe', 'model_C-HR',
       'model_CLA 250 4MATIC Coupe', 'model_CLS 450 4MATIC Coupe',
       'model_CR-V', 'model_CR-V AWD', 'model_CT4', 'model_CT4 AWD',
       'model_CT4-V', 'model_CT4-V AWD', 'model_CT4-V Blackwing',
       'model_CT5', 'model_CT5 AWD', 'model_CT5-V', 'model_CT5-V AWD',
       'model_CT5-V Blackwing', 'model_CX-3', 'model_CX-3 (SIL)',
       'model_CX-3 4WD', 'model_CX-30 4WD', 'model_CX-30 Turbo 4WD',
       'model_CX-5 4WD', 'model_CX-5 4WD (Cylinder Deactivation)',
       'model_CX-5 Turbo 4WD', 'model_CX-9 4WD', 'model_Camaro',
       'model_Camaro SS', 'model_Camaro ZL1', 'model_Camry AWD SE',
       'model_Camry AWD XSE', 'model_Camry Hybrid LE',
       'model_Camry Hybrid SE/XLE/XSE', 'model_Camry LE/SE',
       'model_Camry TRD', 'model_Camry XSE', 'model_Camry XSE V6',
       'model_Canyon', 'model_Canyon 4WD', 'model_Carnival',
       'model_Cayenne', 'model_Cayenne Coupe', 'model_Cayenne GTS',
       'model_Cayenne GTS Coupe', 'model_Cayenne S',
       'model_Cayenne S Coupe', 'model_Cayenne Turbo',
       'model_Cayenne Turbo Coupe', 'model_Cayenne Turbo GT',
       'model_Challenger', 'model_Challenger (MDS)',
       'model_Challenger AWD', 'model_Challenger SRT Hellcat',
       'model_Challenger SRT Hellcat Widebody',
       'model_Challenger Widebody', 'model_Challenger Widebody (MDS)',
       'model_Charger', 'model_Charger (MDS)', 'model_Charger AWD',
       'model_Charger SRT Hellcat Widebody',
       'model_Charger Widebody (MDS)', 'model_Cherokee',
       'model_Cherokee 4X4 Active Drive I',
       'model_Cherokee 4X4 Active Drive Lock', 'model_Chiron',
       'model_Chiron Pur Sport', 'model_Chiron Super Sport',
       'model_Civic Hatchback', 'model_Civic Sedan',
       'model_Civic Sedan Si', 'model_Colorado', 'model_Colorado 4WD',
       'model_Colorado ZR2 4WD', 'model_Compass', 'model_Compass 4X4',
       'model_Continental GT', 'model_Continental GT Convertible',
       'model_Continental GT Convertible Speed',
       'model_Continental GT Speed', 'model_Cooper 3 Door',
       'model_Cooper 5 Door', 'model_Cooper Convertible',
       'model_Cooper Countryman ALL4', 'model_Cooper S 3 Door',
       'model_Cooper S 5 Door', 'model_Cooper S Clubman ALL4',
       'model_Cooper S Convertible', 'model_Cooper S Countryman ALL4',
       'model_Corolla', 'model_Corolla Apex Edition',
       'model_Corolla Cross', 'model_Corolla Cross AWD',
       'model_Corolla Hatchback', 'model_Corolla Hybrid',
       'model_Corolla XLE', 'model_Corolla XSE', 'model_Corsair AWD',
       'model_Corvette', 'model_Crosstrek AWD', 'model_Cullinan',
       'model_Cullinan Black Badge', 'model_DB11 V12', 'model_DB11 V8',
       'model_DBS V12', 'model_DBX V8', 'model_Defender 110 5.0L V8',
       'model_Defender 110 P300', 'model_Defender 110 P400',
       'model_Defender 90 5.0L V8', 'model_Defender 90 P300',
       'model_Defender 90 P400', 'model_Discovery P300',
       'model_Discovery P360', 'model_Durango AWD',
       'model_Durango AWD SRT', 'model_E 350 4MATIC Sedan',
       'model_E 450 4MATIC All-Terrain Wagon',
       'model_E 450 4MATIC Cabriolet', 'model_E 450 4MATIC Coupe',
       'model_E 450 4MATIC Sedan', 'model_E-PACE P250',
       'model_E-PACE P300', 'model_ES 250 AWD', 'model_ES 300h',
       'model_ES 350', 'model_ES 350 F SPORT', 'model_Eclipse Cross 4WD',
       'model_EcoSport AWD', 'model_Edge AWD', 'model_Elantra',
       'model_Elantra (ISG)', 'model_Elantra Hybrid Blue',
       'model_Elantra N', 'model_Enclave', 'model_Enclave AWD',
       'model_Encore', 'model_Encore AWD', 'model_Encore GX',
       'model_Encore GX AWD', 'model_Envision', 'model_Envision AWD',
       'model_Equinox', 'model_Equinox AWD', 'model_Escalade 4WD',
       'model_Escalade 4WD (No Stop-Start)', 'model_Escape',
       'model_Escape AWD', 'model_Escape Hybrid',
       'model_Escape Hybrid AWD', 'model_Expedition 4X4',
       'model_Expedition 4X4 (Without Stop-Start)',
       'model_Expedition Timberline 4X4',
       'model_Expedition Timberline 4X4 (Without Stop-Start)',
       'model_Explorer AWD', 'model_Explorer AWD (Without Stop-Start)',
       'model_Explorer Hybrid AWD', 'model_Explorer Timberline AWD',
       'model_Explorer Timberline AWD (Without Stop-Start)',
       'model_F-150', 'model_F-150 (Without Stop-Start)',
       'model_F-150 4X4', 'model_F-150 4X4 (Without Stop-Start)',
       'model_F-150 4X4 FFV', 'model_F-150 4X4 FFV (Without Stop-Start)',
       'model_F-150 FFV', 'model_F-150 FFV (Without Stop-Start)',
       'model_F-150 Hybrid', 'model_F-150 Hybrid 4X4',
       'model_F-150 Raptor 37 4X4',
       'model_F-150 Raptor 37 4X4 (Without Stop-Start)',
       'model_F-150 Raptor 4X4',
       'model_F-150 Raptor 4X4 (Without Stop-Start)',
       'model_F-150 Tremor 4X4',
       'model_F-150 Tremor 4X4 (Without Stop-Start)',
       'model_F-TYPE P450 Convertible',
       'model_F-TYPE P450 Convertible AWD', 'model_F-TYPE P450 Coupe',
       'model_F-TYPE P450 Coupe AWD', 'model_F-TYPE R Convertible AWD',
       'model_F-TYPE R Coupe AWD', 'model_Flying Spur',
       'model_Forester AWD', 'model_Forester Wilderness AWD',
       'model_Forte', 'model_Forte 5', 'model_Frontier',
       'model_Frontier 4WD', 'model_G70 AWD', 'model_G80 AWD',
       'model_G90 AWD', 'model_GLA 250 4MATIC SUV',
       'model_GLB 250 4MATIC SUV', 'model_GLC 300 4MATIC Coupe',
       'model_GLC 300 4MATIC SUV', 'model_GLE 350 4MATIC SUV',
       'model_GLE 450 4MATIC Coupe', 'model_GLE 450 4MATIC SUV',
       'model_GLS 450 4MATIC SUV', 'model_GR 86', 'model_GR Supra 2.0',
       'model_GR Supra 3.0', 'model_GT', 'model_GV70 AWD',
       'model_GV80 AWD', 'model_GX 460', 'model_Ghibli GT',
       'model_Ghibli Modena', 'model_Ghibli Modena AWD',
       'model_Ghibli Trofeo', 'model_Ghost', 'model_Ghost Black Badge',
       'model_Ghost EWB', 'model_Giulia', 'model_Giulia AWD',
       'model_Giulia Quadrifoglio', 'model_Gladiator 4X4',
       'model_Gladiator 4X4 EcoDiesel',
       'model_Gladiator 4X4 Rubicon EcoDiesel', 'model_Golf GTI',
       'model_Golf R', 'model_Grand Caravan', 'model_Grand Cherokee 4X4',
       'model_Grand Cherokee L 4X4', 'model_Grand Cherokee WK 4X4',
       'model_Grand Wagoneer 4X4', 'model_HR-V', 'model_HR-V AWD',
       'model_Highlander AWD', 'model_Highlander Hybrid AWD',
       'model_Highlander Hybrid AWD Limited/Platinum',
       'model_Huracan evo Coupe', 'model_Huracan evo Coupe AWD',
       'model_Huracan evo Spyder', 'model_Huracan evo Spyder AWD',
       'model_ILX', 'model_IONIQ', 'model_IONIQ Blue', 'model_IS 300',
       'model_IS 300 AWD', 'model_IS 350 AWD', 'model_IS 500',
       'model_Impreza 4-Door AWD', 'model_Impreza 5-Door AWD',
       'model_Jetta', 'model_Jetta GLI', 'model_Jetta SE/SEL',
       'model_John Cooper Works 3 Door',
       'model_John Cooper Works Clubman ALL4',
       'model_John Cooper Works Convertible',
       'model_John Cooper Works Countryman ALL4', 'model_K5',
       'model_K5 AWD', 'model_Kicks', 'model_Kona', 'model_Kona AWD',
       'model_Kona N', 'model_LC 500', 'model_LC 500 Convertible',
       'model_LC 500h', 'model_LS 500 AWD', 'model_LS 500h AWD',
       'model_LX 600', 'model_Legacy AWD', 'model_Levante GT',
       'model_Levante Modena', 'model_Levante Modena V8',
       'model_Levante Trofeo', 'model_M235i xDrive Gran Coupe',
       'model_M240i xDrive Coupe', 'model_M3 Competition Sedan',
       'model_M3 Competition Sedan M xDrive', 'model_M3 Sedan',
       'model_M340i xDrive Sedan',
       'model_M4 Competition Cabriolet M xDrive',
       'model_M4 Competition Coupe',
       'model_M4 Competition Coupe M xDrive', 'model_M4 Coupe',
       'model_M440i xDrive Cabriolet', 'model_M440i xDrive Coupe',
       'model_M440i xDrive Gran Coupe', 'model_M5 CS',
       'model_M5 Competition', 'model_M5 Sedan',
       'model_M550i xDrive Sedan', 'model_M760i xDrive Sedan',
       'model_M8 Cabriolet', 'model_M8 Cabriolet Competition',
       'model_M8 Coupe', 'model_M8 Coupe Competition',
       'model_M8 Gran Coupe', 'model_M8 Gran Coupe Competition',
       'model_M850i xDrive Cabriolet', 'model_M850i xDrive Coupe',
       'model_M850i xDrive Gran Coupe', 'model_MC20', 'model_MDX SH-AWD',
       'model_MX-5', 'model_MX-5 (SIL)', 'model_Macan', 'model_Macan GTS',
       'model_Macan S', 'model_Malibu', 'model_Maverick AWD',
       'model_Maverick Hybrid', 'model_Maxima',
       'model_Maybach S 580 4MATIC Sedan', 'model_Mazda3 4-Door',
       'model_Mazda3 4-Door (SIL)', 'model_Mazda3 4-Door 4WD',
       'model_Mazda3 4-Door Turbo 4WD', 'model_Mazda3 5-Door',
       'model_Mazda3 5-Door (SIL)', 'model_Mazda3 5-Door 4WD',
       'model_Mazda3 5-Door Turbo 4WD', 'model_Metris Cargo Van',
       'model_Metris Cargo Van LWB', 'model_Metris Passenger Van',
       'model_Mirage', 'model_Murano AWD', 'model_Mustang',
       'model_Mustang (High Performance)', 'model_Mustang Convertible',
       'model_Mustang Convertible (High Performance)',
       'model_Mustang Mach 1', 'model_NX 250 AWD', 'model_NX 350 AWD',
       'model_NX 350 AWD F SPORT', 'model_NX 350h AWD',
       'model_Nautilus AWD', 'model_Navigator 4X4', 'model_Niro',
       'model_Niro FE', 'model_Niro Touring', 'model_Odyssey',
       'model_Outback AWD', 'model_Outback Wilderness AWD',
       'model_Outlander 4WD', 'model_Pacifica', 'model_Pacifica AWD',
       'model_Palisade AWD', 'model_Panamera', 'model_Panamera 4',
       'model_Panamera 4 Executive', 'model_Panamera 4 ST',
       'model_Panamera 4S', 'model_Panamera 4S Executive',
       'model_Panamera 4S ST', 'model_Panamera GTS',
       'model_Panamera GTS ST', 'model_Panamera Turbo S',
       'model_Panamera Turbo S Executive', 'model_Panamera Turbo S ST',
       'model_Passat', 'model_Passport AWD', 'model_Pathfinder 4WD',
       'model_Phantom', 'model_Phantom EWB', 'model_Pilot AWD',
       'model_Pilot AWD TrailSport', 'model_Prius', 'model_Prius AWD',
       'model_ProMaster City', 'model_Q3 40 TFSI quattro',
       'model_Q3 45 TFSI quattro', 'model_Q5 40 TFSI quattro',
       'model_Q5 45 TFSI quattro', 'model_Q5 Sportback 45 TFSI quattro',
       'model_Q50 AWD', 'model_Q50 AWD Red Sport', 'model_Q60 AWD',
       'model_Q60 AWD Red Sport', 'model_Q7 45 TFSI quattro',
       'model_Q7 55 TFSI quattro', 'model_Q8 55 TFSI quattro',
       'model_QX50 AWD', 'model_QX55 AWD', 'model_QX60 AWD',
       'model_QX80 4WD', 'model_Qashqai', 'model_Qashqai AWD',
       'model_Quattroporte GT', 'model_Quattroporte Modena',
       'model_Quattroporte Modena AWD', 'model_Quattroporte Trofeo',
       'model_R8 Coupe Performance', 'model_R8 Coupe Performance quattro',
       'model_R8 Spyder Performance',
       'model_R8 Spyder Performance quattro', 'model_RAV4',
       'model_RAV4 (Stop/Start)', 'model_RAV4 AWD',
       'model_RAV4 AWD (Stop/Start)', 'model_RAV4 AWD LE',
       'model_RAV4 AWD TRD Off-Road', 'model_RAV4 Hybrid AWD',
       'model_RC 300 AWD', 'model_RC 350 AWD', 'model_RC F',
       'model_RDX SH-AWD', 'model_RDX SH-AWD A-SPEC',
       'model_RS 5 Coupe quattro', 'model_RS 5 Sportback quattro',
       'model_RS 6 Avant quattro', 'model_RS 7 Sportback quattro',
       'model_RS Q8 quattro', 'model_RVR', 'model_RVR 4WD',
       'model_RX 350 AWD', 'model_RX 350 L AWD', 'model_RX 450h AWD',
       'model_RX 450h L AWD', 'model_Range Rover P360',
       'model_Range Rover P400', 'model_Range Rover P525',
       'model_Range Rover P525 LWB', 'model_Range Rover SVAutobiography',
       'model_Range Rover SVAutobiography LWB',
       'model_Range Rover Sport HST P400', 'model_Range Rover Sport P360',
       'model_Range Rover Sport P525', 'model_Range Rover Sport P575 SVR',
       'model_Ranger 4WD', 'model_Ranger 4WD (Without Stop-Start)',
       'model_Ranger 4WD Tremor', 'model_Renegade', 'model_Renegade 4X4',
       'model_Renegade 4X4 Trailhawk', 'model_Ridgeline AWD', 'model_Rio',
       'model_Rogue', 'model_Rogue AWD', 'model_Rogue AWD SL/Platinum',
       'model_S 500 4MATIC SWB Sedan', 'model_S 580 4MATIC LWB Sedan',
       'model_S3 Sedan quattro', 'model_S4 Sedan quattro',
       'model_S5 Cabriolet quattro', 'model_S5 Coupe quattro',
       'model_S5 Sportback quattro', 'model_S6 Sedan quattro',
       'model_S60 B5', 'model_S60 B5 AWD', 'model_S7 Sportback quattro',
       'model_S8 Sedan quattro', 'model_S90 B6 AWD',
       'model_SQ5 Sportback quattro', 'model_SQ5 quattro',
       'model_SQ7 quattro', 'model_SQ8 quattro', 'model_Santa Cruz AWD',
       'model_Santa Fe AWD', 'model_Santa Fe Hybrid', 'model_Seltos',
       'model_Seltos AWD', 'model_Sentra', 'model_Sentra SR',
       'model_Sequoia 4WD', 'model_Shelby GT500 Mustang', 'model_Sienna',
       'model_Sienna AWD', 'model_Sierra', 'model_Sierra 4WD',
       'model_Sierra 4WD (No DFM)', 'model_Sierra 4WD (No Stop-Start)',
       'model_Sierra 4WD (With Sport Mode)', 'model_Sierra 4WD FFV',
       'model_Sierra 4WD Mud Terrain Tire',
       'model_Sierra 4WD Mud Terrain Tire (No DFM)',
       'model_Sierra 4WD Mud Terrain Tire (No Stop-Start)',
       'model_Sierra 4WD Mud Terrain Tire FFV', 'model_Sierra FFV',
       'model_Silverado', 'model_Silverado 4WD',
       'model_Silverado 4WD (No DFM)',
       'model_Silverado 4WD (No Stop-Start)',
       'model_Silverado 4WD (With Sport Mode)',
       'model_Silverado 4WD Custom Trail Boss', 'model_Silverado 4WD FFV',
       'model_Silverado 4WD Mud Terrain Tire',
       'model_Silverado 4WD Mud Terrain Tire (No DFM)',
       'model_Silverado 4WD Mud Terrain Tire (No Stop-Start)',
       'model_Silverado 4WD Mud Terrain Tire FFV',
       'model_Silverado 4WD ZR2', 'model_Silverado FFV', 'model_Sonata',
       'model_Sonata Hybrid', 'model_Sorento AWD',
       'model_Sorento Hybrid AWD', 'model_Soul', 'model_Spark',
       'model_Sportage', 'model_Sportage AWD', 'model_Stelvio',
       'model_Stelvio AWD', 'model_Stelvio AWD Quadrifoglio',
       'model_Stinger AWD', 'model_Suburban',
       'model_Suburban (No Stop-Start)', 'model_Suburban 4WD',
       'model_Suburban 4WD (No Stop-Start)', 'model_TLX SH-AWD',
       'model_TLX SH-AWD A-SPEC', 'model_TLX Type S',
       'model_TLX Type S (Performance Tire)',
       'model_TT Coupe 45 TFSI quattro', 'model_TT RS Coupe quattro',
       'model_TT Roadster 45 TFSI quattro', 'model_TTS Coupe quattro',
       'model_Tacoma 4WD', 'model_Tacoma 4WD D-Cab TRD Off-Road/PRO',
       'model_Tahoe', 'model_Tahoe (No Stop-Start)', 'model_Tahoe 4WD',
       'model_Tahoe 4WD (No Stop-Start)', 'model_Taos',
       'model_Taos 4MOTION', 'model_Telluride AWD', 'model_Terrain',
       'model_Terrain AWD', 'model_Tiguan 4MOTION',
       'model_Tiguan R-Line 4MOTION', 'model_Trailblazer',
       'model_Trailblazer AWD', 'model_Transit Connect Van',
       'model_Transit Connect Van FFV', 'model_Transit Connect Wagon LWB',
       'model_Transit Connect Wagon LWB FFV', 'model_Traverse',
       'model_Traverse AWD', 'model_Trax', 'model_Trax AWD',
       'model_Tucson', 'model_Tucson AWD', 'model_Tucson Hybrid',
       'model_Tundra', 'model_Tundra 4WD', 'model_Tundra 4WD TRD',
       'model_Tundra Hybrid 4WD', 'model_Tundra Hybrid 4WD TRD PRO',
       'model_UX 200', 'model_UX 250h AWD', 'model_Urus',
       'model_V60 CC T5 AWD', 'model_V60 T6 AWD', 'model_V90 CC B6 AWD',
       'model_Vantage V8', 'model_Veloster N', 'model_Venue',
       'model_Venza AWD', 'model_Versa', 'model_WRX AWD',
       'model_Wagoneer 4X4', 'model_Wrangler JL 4X4',
       'model_Wrangler JL 4X4 eTorque', 'model_Wrangler JL Unlimited 4X4',
       'model_Wrangler JL Unlimited 4X4 EcoDiesel',
       'model_Wrangler JL Unlimited 4X4 Rubicon EcoDiesel',

In [53]:
t = pd.DataFrame(l,columns=c)
t

,make_Acura,make_Alfa Romeo,make_Aston Martin,make_Audi,make_BMW,make_Bentley,make_Bugatti,make_Buick,make_Cadillac,make_Chevrolet,...,transmission_AV6,transmission_AV7,transmission_AV8,transmission_M5,transmission_M6,transmission_M7,fuel_D,fuel_E,fuel_X,fuel_Z
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [54]:
l2 = check.iloc[:,5:]

In [55]:
l2

   engine  cylinder  co2  smokerating
0     2.4         4  200            3

In [56]:
final = pd.concat([l2,t],axis=1)
final

,engine,cylinder,co2,smokerating,make_Acura,make_Alfa Romeo,make_Aston Martin,make_Audi,make_BMW,make_Bentley,...,transmission_AV6,transmission_AV7,transmission_AV8,transmission_M5,transmission_M6,transmission_M7,fuel_D,fuel_E,fuel_X,fuel_Z
0,2.4,4,200,3,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [57]:
final_model = joblib.load("regressor.pkl")
final_model

RandomForestRegressor(max_depth=8, max_features='auto')

In [58]:
final_model.predict(final)

array([33.03])